### ISSUE TITLE
OpenApi viewer service

### ISSUE THREAD

**Issue by nicolas-bonnel** [Mermade/awesome-openapi3#2]
Hi,

I just built a little service that uses [our component](https://github.com/koumoul-dev/vue-openapi).

https://github.com/koumoul-dev/openapi-viewer

I'll try to deploy it soon in cloud and add format validation later

**Comment by MikeRalphson** [comment]
Have made the main link to this project, with a reference to the vue.js component. Please let me know when there's a hosted version available.

**Comment by nicolas-bonnel** [comment]
We host the service here https://koumoul.com/openapi-viewer/

I also pushed a [docker image](https://hub.docker.com/r/koumoul/openapi-viewer/) to docker hub and the service can be launched with :
```
docker run -p 8080:8080 koumoul/openapi-viewer
```

**Comment by MikeRalphson** [comment]
Updated. Please shout if you think the projects/links should be listed differently.
