### ISSUE TITLE
SwagEdit and RepreZen API Studio

### ISSUE THREAD

**Issue by tedepstein** [Mermade/awesome-openapi3#4]
Thanks for adding the link to [KaiZen OpenAPI Parser](https://github.com/reprezen/kaizen-openapi-parser)!

Two others coming soon (in May-June timeframe):

* [SwagEdit](https://github.com/reprezen/swagedit), open source Swagger-OpenAPI editor for Eclipse IDE.

* [RepreZen API Studio](http://reprezen.com/swagger-tools), our commercial API design, documentation & development platform.

**Comment by MikeRalphson** [comment]
Hi @tedepstein I've now added the links to KaiZen Editor and RepreZen API Studio as I spotted an article on them at ProgrammableWeb.
